<!DOCTYPE html>
<html lang="hu">
<head>
</head>
<body>
    <table style="width:100%">
        <tr>
          <th>Csengetés</th>
          <th>Hétfő</th>
          <th>Kedd</th>
          <th>Szerda</th>
          <th>Csütörtök</th>
          <th>Péntek</th>
        </tr>
        <tr>
          <td>8-8.45</td>
          <td>Nyelvtan</td>
          <td>Angol</td>
          <td>Matek</td>
          <td>Nyelvtan</td>
          <td>Angol</td>
          
        </tr>
        <tr>
          <td>8.55-9.40</td>
          <td>Osztályfőnöki</td>
          <td>Komplex</td>
          <td>Töri</td>
          <td>Prog alap</td>
          <td>Komplex</td>
        </tr>
        <tr>
            <td>9.50-10.35</td>
            <td>Magyar(komp)</td>
            <td>Matek</td>
            <td>Info és távk</td>
            <td>Prog alap</td>
            <td>IKT projektmunka</td>
          </tr>
          <tr>
            <td>10.45-11.30</td>
            <td>Tesi</td>
            <td>Töri</td>
            <td>Info és távk</td>
            <td>Angol</td>
            <td>Tesi</td>
          </tr>
          <tr>
            <td>11.40-12.25</td>
            <td>Munkavállaló</td>
            <td>Irodalom</td>
            <td>Info és távk</td>
            <td>Matek</td>
            <td>Matek(komp)</td>
          </tr>
          <tr>
            <td>12.45-13.30</td>
            <td>Töri</td>
            <td>Tesi</td>
            <td>Angol</td>
            <td>Irodalom</td>
            <td>Matek</td>
          </tr>
          <tr>
            <td>13.35-14.20</td>
            <td>------</td>
            <td>------</td>
            <td>Digit kult</td>
            <td>Komplex</td>
          </tr>
          <tr>
            <td>14.25-15.10</td>
            <td>------</td>
            <td>------</td>
            <td>Digit kult</td>
          </tr>
      </table>
</body>
</html>
